from __future__ import annotations

import argparse
import hashlib
import sys
import tempfile
from pathlib import Path


SKILL_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = SKILL_ROOT / "gpt" / "owner-biography-knowledge.md"
SOURCES = (
    (
        "Research and dossier contract",
        Path("references/research-contract.md"),
    ),
    (
        "Wealth classification",
        Path("references/wealth-classification.md"),
    ),
    (
        "Biography style",
        Path("references/biography-style.md"),
    ),
    (
        "Editorial calibrations",
        Path("references/editorial-calibrations.md"),
    ),
)
LINK_REWRITES = {
    "](wealth-classification.md)": "](#wealth-classification)",
    "](biography-style.md)": "](#biography-style)",
    "](editorial-calibrations.md)": "](#editorial-calibrations)",
}


def _source_text(relative_path: Path) -> str:
    text = (SKILL_ROOT / relative_path).read_text(encoding="utf-8")
    for source, target in LINK_REWRITES.items():
        text = text.replace(source, target)
    return text.strip()


def _sha256(relative_path: Path) -> str:
    content = (SKILL_ROOT / relative_path).read_bytes()
    return hashlib.sha256(content).hexdigest()


def render_knowledge() -> str:
    contents = "\n".join(
        f"- [{title}](#{title.lower().replace(' ', '-').replace('&', '')})"
        for title, _ in SOURCES
    )
    provenance = "\n".join(
        f"| {title} | `{relative_path.as_posix()}` | `{_sha256(relative_path)}` |"
        for title, relative_path in SOURCES
    )
    sections = "\n\n---\n\n".join(
        _source_text(relative_path)
        for _, relative_path in SOURCES
    )
    return (
        "# Owner Biography Research Knowledge\n\n"
        "> Generated by `scripts/build_gpt_knowledge.py` from the canonical "
        "skill references. Do not edit this file directly.\n\n"
        "Use this file as Custom GPT Knowledge. Behaviour, workflow order, "
        "manual-mode rules, and delivery requirements belong in the GPT "
        "Instructions supplied separately in `gpt/instructions.md`. The "
        "canonical references below also describe repository-backed scripts "
        "and owner-input validation; treat those passages as reference only "
        "during a name-and-context GPT run and follow the GPT Instructions "
        "instead. Access to repository scripts, schemas, owner input, Code "
        "Interpreter, or downloadable files is never required to produce the "
        "complete human-readable research profile.\n\n"
        "## Contents\n\n"
        f"{contents}\n\n"
        "## Provenance\n\n"
        "| Section | Canonical source | SHA-256 |\n"
        "| --- | --- | --- |\n"
        f"{provenance}\n\n"
        "---\n\n"
        f"{sections}\n"
    )


def _write_output(content: str) -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        newline="\n",
        delete=False,
        dir=OUTPUT_PATH.parent,
        prefix=f".{OUTPUT_PATH.name}.",
        suffix=".tmp",
    ) as handle:
        handle.write(content)
        temporary_path = Path(handle.name)
    temporary_path.replace(OUTPUT_PATH)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build or verify the Custom GPT Knowledge file.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the tracked Knowledge file is missing or stale.",
    )
    args = parser.parse_args()

    expected = render_knowledge()
    if args.check:
        if not OUTPUT_PATH.exists():
            print(
                f"Missing generated Knowledge file: {OUTPUT_PATH}",
                file=sys.stderr,
            )
            return 1
        actual = OUTPUT_PATH.read_text(encoding="utf-8")
        if actual != expected:
            print(
                "Custom GPT Knowledge is stale; run "
                "scripts/build_gpt_knowledge.py.",
                file=sys.stderr,
            )
            return 1
        print(f"Custom GPT Knowledge is current: {OUTPUT_PATH}")
        return 0

    _write_output(expected)
    print(f"Wrote Custom GPT Knowledge: {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
