from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tempfile
import zipfile
from pathlib import Path
from urllib.parse import unquote, urlsplit


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.tags import TagCatalogue


SKILL_ROOT = REPO_ROOT / ".agents" / "skills" / "research-owner-biography"
PLUGIN_ROOT = REPO_ROOT / "plugins" / "yacht-owner-biography-researcher"
PLUGIN_SKILL = PLUGIN_ROOT / "skills" / "research-owner-biography"
PLUGIN_REFERENCES = PLUGIN_SKILL / "references"
OUTPUT_PATH = PLUGIN_REFERENCES / "owner-biography-knowledge.md"
TAG_CATALOGUE_SOURCE = REPO_ROOT / "config" / "owner-tags.json"
TAG_CATALOGUE_OUTPUT = PLUGIN_REFERENCES / "tag-catalogue.json"
EXAMPLE_SOURCE = SKILL_ROOT / "references" / "manual-dossier.example.json"
EXAMPLE_OUTPUT = PLUGIN_REFERENCES / "manual-dossier.example.json"
TAG_REPO_PATH = TAG_CATALOGUE_OUTPUT.relative_to(REPO_ROOT).as_posix()
SOURCES = (
    (
        "Owner tag governance",
        Path("../../../docs/ai/OWNER_TAG_GOVERNANCE.md"),
    ),
    (
        "Research and dossier contract",
        Path("references/research-contract.md"),
    ),
    (
        "Wealth classification",
        Path("references/wealth-classification.md"),
    ),
    (
        "Biography style",
        Path("references/biography-style.md"),
    ),
    (
        "Editorial calibrations",
        Path("references/editorial-calibrations.md"),
    ),
)
LINK_REWRITES = {
    "](wealth-classification.md)": "](#wealth-classification)",
    "](biography-style.md)": "](#biography-style)",
    "](editorial-calibrations.md)": "](#editorial-calibrations)",
    "](../../../../docs/ai/OWNER_TAG_GOVERNANCE.md)": "](#owner-tag-governance)",
}


def _source_text(relative_path: Path) -> str:
    text = (SKILL_ROOT / relative_path).read_text(encoding="utf-8")
    for source, target in LINK_REWRITES.items():
        text = text.replace(source, target)
    text = text.replace(TAG_REPO_PATH, "tag-catalogue.json")
    return text.strip()


def _sha256(relative_path: Path) -> str:
    content = (SKILL_ROOT / relative_path).read_text(encoding="utf-8").encode("utf-8")
    return hashlib.sha256(content).hexdigest()


def render_knowledge() -> str:
    contents = "\n".join(
        f"- [{title}](#{title.lower().replace(' ', '-').replace('&', '')})"
        for title, _ in SOURCES
    )
    provenance = "\n".join(
        f"| {title} | `{relative_path.as_posix()}` | `{_sha256(relative_path)}` |"
        for title, relative_path in SOURCES
    )
    sections = "\n\n---\n\n".join(
        _source_text(relative_path)
        for _, relative_path in SOURCES
    )
    return (
        "# Owner Biography Research Knowledge\n\n"
        "> Generated by `tools/build_plugin.py` from the canonical "
        "skill references. Do not edit this file directly.\n\n"
        "This is a bundled plugin reference. Behaviour, workflow order, "
        "manual-mode rules, and delivery requirements belong in the "
        "SKILL.md entrypoint one directory above this file. The "
        "canonical references below also describe repository-backed scripts "
        "and owner-input validation; treat those passages as reference only "
        "during a name-and-context plugin run and follow the skill instructions "
        "instead. Access to repository scripts, schemas, owner input, Code "
        "Interpreter, or downloadable files is never required to produce the "
        "complete human-readable research profile.\n\n"
        "## Contents\n\n"
        f"{contents}\n\n"
        "## Provenance\n\n"
        "| Section | Canonical source | SHA-256 |\n"
        "| --- | --- | --- |\n"
        f"{provenance}\n\n"
        "---\n\n"
        f"{sections}\n"
    )


def render_tag_catalogue() -> str:
    source = json.loads(TAG_CATALOGUE_SOURCE.read_text(encoding="utf-8"))
    catalogue = TagCatalogue(source, source=str(TAG_CATALOGUE_SOURCE))
    active = [
        {
            "id": item["id"],
            "name": item["name"],
            "normalized_name": item["normalized_name"],
            "aliases": item["aliases"],
            "facets": item["facets"],
            "semantic_contract": item["semantic_contract"],
        }
        for item in source["tags"]
        if item["id"] in catalogue.tags_by_id
    ]
    output = {
        "schema_version": 3,
        "dataset": "owner_tag_active_catalogue",
        "description": (
            "Closed-world whitelist for individual owner research. Only these "
            "active approved canonical tags and their aliases may be assigned."
        ),
        "tags": active,
    }
    return json.dumps(output, ensure_ascii=False, indent=2) + "\n"


def _write_output(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        newline="\n",
        delete=False,
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    ) as handle:
        handle.write(content)
        temporary_path = Path(handle.name)
    temporary_path.replace(path)


def generated_files() -> dict[Path, str]:
    return {
        OUTPUT_PATH: render_knowledge(),
        TAG_CATALOGUE_OUTPUT: render_tag_catalogue(),
        EXAMPLE_OUTPUT: EXAMPLE_SOURCE.read_text(encoding="utf-8"),
    }


def check_generated() -> None:
    for path, expected in generated_files().items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            raise ValueError(f"Missing or stale plugin reference: {path}; run python tools/build_plugin.py")


def validate_plugin(plugin_root: Path = PLUGIN_ROOT) -> list[Path]:
    """Check the portable skills-only package, including an isolated extraction."""
    manifest = json.loads((plugin_root / "plugin.json").read_text(encoding="utf-8"))
    if manifest.get("$schema") != "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json":
        raise ValueError("Expected portable Agent Plugins 1.0 manifest")
    if manifest.get("name") != plugin_root.name:
        raise ValueError("Plugin name must match its directory")
    if not re.fullmatch(r"(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)", manifest.get("version", "")):
        raise ValueError("Use a three-part numeric release version")
    if not manifest.get("description") or not manifest.get("author", {}).get("name"):
        raise ValueError("Plugin description and author are required")
    if set(manifest) - {"$schema", "name", "version", "description", "author", "extensions"}:
        raise ValueError("New manifest fields require a deliberate validator/builder update")
    extension = manifest.get("extensions", {}).get("com.openai", {})
    if set(extension) != {"interface"}:
        raise ValueError("This builder supports the skills-only plugin without integrations")
    interface = extension["interface"]
    for key in ("displayName", "shortDescription", "longDescription", "developerName", "category"):
        if not isinstance(interface.get(key), str) or not interface[key].strip():
            raise ValueError(f"Missing plugin interface.{key}")
    prompts = interface.get("defaultPrompt")
    if isinstance(prompts, str):
        prompts = [prompts]
    if not isinstance(prompts, list) or not 1 <= len(prompts) <= 3 or not all(isinstance(p, str) and p.strip() for p in prompts):
        raise ValueError("Expected one to three starter prompts")
    runtime = plugin_root / "skills" / "research-owner-biography"
    expected = [plugin_root / "plugin.json", runtime / "SKILL.md"]
    expected.extend(runtime / "references" / name for name in (
        "owner-biography-knowledge.md", "tag-catalogue.json", "manual-dossier.example.json",
    ))
    actual = [p for p in (plugin_root / "skills").rglob("*") if p.is_file()]
    if set(actual) != set(expected[1:]):
        raise ValueError("Missing or unexpected runtime files; package only the maintained skill and its three references")
    for path in [plugin_root, *plugin_root.rglob("*")]:
        if path.is_symlink() or getattr(path, "is_junction", lambda: False)():
            raise ValueError(f"Plugin links/junctions are not supported: {path}")
    skill = (runtime / "SKILL.md").read_text(encoding="utf-8")
    if not skill.startswith("---\nname: research-owner-biography\ndescription: ") or "\n---\n" not in skill[4:]:
        raise ValueError("Skill requires matching name and description frontmatter")
    for path in expected:
        if not path.is_file():
            raise ValueError(f"Missing runtime file: {path}")
        if path.suffix == ".json":
            json.loads(path.read_text(encoding="utf-8"))
        if path.suffix == ".md":
            for target in re.findall(r"\[[^\]\n]+\]\(([^)\n]+)\)", path.read_text(encoding="utf-8")):
                parts = urlsplit(target.strip("<>"))
                if parts.scheme or not parts.path:
                    continue
                linked = (path.parent / unquote(parts.path)).resolve()
                if not linked.is_relative_to(plugin_root.resolve()) or not linked.is_file():
                    raise ValueError(f"Missing or external runtime reference: {target}")
    return expected


def package_plugin(output_dir: Path | None = None) -> Path:
    check_generated()
    files = validate_plugin()
    output_dir = output_dir or REPO_ROOT / "dist"
    output_dir.mkdir(parents=True, exist_ok=True)
    version = json.loads((PLUGIN_ROOT / "plugin.json").read_text(encoding="utf-8"))["version"]
    archive_path = output_dir / f"{PLUGIN_ROOT.name}-{version}.zip"
    with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(files):
            name = f"{PLUGIN_ROOT.name}/{path.relative_to(PLUGIN_ROOT).as_posix()}"
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            info.create_system = 3
            archive.writestr(info, path.read_text(encoding="utf-8").encode("utf-8"))
    with zipfile.ZipFile(archive_path) as archive:
        if archive.testzip() is not None:
            raise ValueError("Archive failed its CRC check")
    digest = hashlib.sha256(archive_path.read_bytes()).hexdigest()
    archive_path.with_suffix(".zip.sha256").write_text(f"{digest}  {archive_path.name}\n", encoding="utf-8")
    return archive_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate, verify or package the Yacht Owner Biography Researcher plugin.")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Check freshness and package structure without writing.")
    mode.add_argument("--package", action="store_true", help="Check freshness and build one ZIP and checksum under dist/.")
    args = parser.parse_args()
    try:
        if args.package:
            print(package_plugin())
        elif args.check:
            check_generated()
            validate_plugin()
            print("Plugin package and generated references are current")
        else:
            for path, content in generated_files().items():
                _write_output(path, content)
                print(f"Wrote plugin reference: {path}")
            validate_plugin()
    except (OSError, ValueError, KeyError) as error:
        print(str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
